name: Container

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine3.12
    steps:
      - name: Log node version
        run: node -v

      - name: Step with docker
        uses: docker://node:14-alpine
        with:
          entrypoint: /bin/echo
          args: Hello World!!

      - name: Log node version
        uses: docker://node:14-alpine
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v2
      - name: Run a script
        uses: docker://node:14-alpine
        with:
          entrypoint: ./script.sh
          args: "Some String"
          
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: Node version
        run: |
          node -v
          cat /etc/os-release
    


     