name: Matrix

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [10,12,14]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Node version
        run: node -v

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Node version
        run: node -v