name: Matrix

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [10,12,14]
        include:
          - os: ubuntu-latest
            node_version: 10
            is_ubuntu_8: true
        exclude: 
          - os: ubuntu-latest
            node_version: 10
          - os: macos-latest
            node_version: 12

    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Node version
        run: node -v

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Node version
        run: |
          node -v
          echo $IS_UBUNTU_8