name: Matrix

on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Node version
        run: node -v

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 6
          
      - name: Node version
        run: node -v